#!/bin/bash

CONTAINER_NAME=betty-rstudio
docker rm -f ${CONTAINER_NAME}
docker run -d \
  --name ${CONTAINER_NAME} \
  -p 8787:8787 \
  -e PASSWORD=xin \
  --memory="48g" \
  --memory-swap="-1" \
  -v /Users/seancheey/unsynced_workspace/RStudioData:/home/rstudio/data \
  sean/rstudio-v4

ps aux | grep autossh | awk '{print $2}' | head -n 1 | xargs -r kill -9
autossh -f -M 8788 -N -R 80:localhost:8787 root@108.160.134.13

open "http://localhost:8787/"
